### ISSUE TITLE
Problem in building this image, erroring out on step 5 (setup_r.sh) of dockerfile

### ISSUE THREAD

**Issue by Analect** [rothnic/datascience-notebook#1]
Hi @rothnic 
Thanks for putting this together.
I pulled the latest version of rothnic/anaconda-notebook ... and was looking to extend to include R, as per this repo .. but hitting some issues, which might be resulting from this repo being out of synch with the more recently updated anaconda-notebook.

Any pointers much appreciated.
Thanks.

```
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# $ source activate r
#
# To deactivate this environment, use:
# $ source deactivate
#
 ---> 4900f86bd8fd
Removing intermediate container 0c80587ae91b
Step 5 : RUN /tmp/setup_r.sh
 ---> Running in 91bde6a5155a
Traceback (most recent call last):
  File "/home/condauser/anaconda3/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/condauser/anaconda3/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/condauser/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/home/condauser/anaconda3/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/home/condauser/anaconda3/lib/python3.4/site-packages/IPython/kernel/kernelspecapp.py", line 142, in start
    return self.subapp.start()
  File "/home/condauser/anaconda3/lib/python3.4/site-packages/IPython/kernel/kernelspecapp.py", line 83, in start
    replace=self.replace,
  File "/home/condauser/anaconda3/lib/python3.4/site-packages/IPython/kernel/kernelspec.py", line 195, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/condauser/anaconda3/lib/python3.4/shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/condauser/anaconda3/envs/r/lib/R/library/IRkernel/kernelspec'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

cp: cannot create regular file '/home/condauser/.ipython/kernels/ir/kernel.json': No such file or directory
```

**Comment by Analect** [comment]
@rothnic 
Was attempting to get to the bottom of this problem with the build failing on setup_r.sh
From running a container based off the half-baked image (before the error above), It seems the step to set up the .Rprofile didn't appear to work.

Also, it seems the version of libstdc is now 6.0.19 .. not sure if relevant

```
ln -s /usr/lib/libstdc++.so.6.0.14 $R_PATH/lib/libstdc++.so.6
```

Also, the step to run the batch install_r_packages.R appears to fail with this error when it tries to load the devtools library.

```
> library(devtools)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/condauser/anaconda3/envs/r/lib/R/library/git2r/libs/git2r.so':
  libssl.so.6: cannot open shared object file: No such file or directory
Error: package or namespace load failed for 'devtools'
```

While the git2r.so file exists, the libssl.so.6 (not sure if meant to be in same directory) does not.

```
/home/condauser/anaconda3/envs/r/lib/R/library/git2r/libs
root@9eb8ac7093bd:~/anaconda3/envs/r/lib/R/library/git2r/libs# ls -ltr
total 1496
-rwxr-xr-x 2 root root 1530656 Jul 28 20:05 git2r.so
```

I'm out of my depth here! ... so will leave this for now.

**Comment by rothnic** [comment]
Hi, yeah I kind of stalled out on getting this working due to wanting to go back and work on the anaconda-notebook that it is based on. I just realized I didn't push a change to this repo that maybe will fix the issue. Try it out and let me know.

**Comment by Analect** [comment]
@rothnic 
Thanks.  Pulled your latest changes and re-ran, but still somehow getting stuck here:

```
Step 4 : RUN /tmp/setup_r.sh
 ---> Running in 4252ba7ca45c
cp: cannot create regular file '/home/condauser/.ipython/kernels/ir/kernel.json': No such file or directory
The command '/bin/sh -c /tmp/setup_r.sh' returned a non-zero code: 1
```

**Comment by Analect** [comment]
@rothnic 
It looks like there was no 'kernels' directory structure automatically created under the .ipython config folder.  Is it a case of adding some commands to do this manually, or is it more involved?

```
condauser@49a97bf9759c:/tmp$ cd /home/condauser/.ipython/
condauser@49a97bf9759c:~/.ipython$ ls -ltr
total 16
drwxr-xr-x 2 condauser condauser 4096 Aug  4 19:07 nbextensions
drwxr-xr-x 2 condauser condauser 4096 Aug  4 19:07 extensions
-rw-r--r-- 1 condauser condauser  195 Aug  4 19:07 README
drwxr-xr-x 8 condauser condauser 4096 Aug  4 19:07 profile_default
```

https://ipython.org/ipython-doc/dev/development/kernels.html

**Comment by rothnic** [comment]
Yeah I set things up again and tried building it locally. I'll play around with it, but remember wavering between doing the install manually, and using the conda r kernel package. At some point I remember installing the kernel seemed to be strange in that it would work sometimes and not others, and might have had to try to install it twice to get it to work, before the kernel.json would be copied over.

This is the call that is supposed to add the folder structure: https://github.com/rothnic/datascience-notebook/blob/master/src/add_kernel.R, but can't remember if that is required if I install via conda instead.

**Comment by Analect** [comment]
This isn't necessarily conda-related, but I did come across this other approach to installing the R kernel on a more simplified Jupyter set-up (Python 2 only, I think), with very few pre-installed packages/libraries.  However, it might be useful to compare/contrast this approach:

https://github.com/adrianliaw/docker-jupyter-irkernel/commit/3a2d7e869197a8edcc4ced3fbf3187f4ca3c5165

**Comment by rothnic** [comment]
Yeah, that is similar to the original approach I took, but it had similar issues. I expected the conda package to makes things easier, which might of been where I left it.

**Comment by rothnic** [comment]
Pushed a change that should make it build. Things seem to work ok, but I couldn't get the ggplot2 outputs to go into the notebook, instead of being saved locally as pdf files.

I'm not sure how mature the anaconda R capability is, and how much it lags. I don't know if there is just an old version or what.

**Comment by Analect** [comment]
@rothnic 
Thanks for your help with this. Got it up and running ... also with tmpnb, as per your readme ... although how does one safely run-down those containers in an automated way?

Ref. ggplot2 ... if I do a 'conda list' ... r-ggplot2 doesn't show up as installed in the datascience-notebook.  Is that expected?

![image](https://cloud.githubusercontent.com/assets/4063815/9099271/5b15feba-3bc7-11e5-9603-d0a2e7ee99eb.png)

Here are the various r-\* libraries installed:
![image](https://cloud.githubusercontent.com/assets/4063815/9099296/8175edfe-3bc7-11e5-9426-95d6b41a81d1.png)
![image](https://cloud.githubusercontent.com/assets/4063815/9099303/8e96542e-3bc7-11e5-918b-f8e28024fd0d.png)

**Comment by rothnic** [comment]
Yeah, I have wavered between including everything vs basic stuff. The whole approach for this compared to some of the other options was to avoid compilation of packages as much as possible via conda installation.

This does remind me that I need to add the r channel to conda, but you can do something like this:

`conda install -c r r-ggplot2` from the command line

Or, if it is some other package, you can go into the R console or an ipython notebook with the r kernel and do `install.packages('ggplot2')`, but this will likely perform some compilation, which is less likely to work and will take some time.

Also, what do you mean "run down".

**Comment by Analect** [comment]
OK. Thanks for info.
Just on the tmpnb stuff ... which I know you have some experience leveraging ... can't find in documentation, but to bring back down the environment with multiple containers .. is there an automated way?

**Comment by rothnic** [comment]
You can do that in a few ways based on how you ran it. I typically just would run the tmpnb components from different shells, non-detached if you are messing with things. Then you can ctrl-c to close them.

Otherwise, you can list them via `docker ps`, then `docker stop` them by name.

**Comment by Analect** [comment]
Thanks. I'll close this out. Appreciate your help in getting the datascience-notebook up and running.
